##### %pip install pandas

In [1]:
import numpy as np
import pandas as pd

In [5]:
# 1. Create a NumPy array of integers from 0 to 5 and print its data type.

arr = np.array([0, 1, 2, 3, 4, 5])

print(arr)
print(arr.dtype)

[0 1 2 3 4 5]
int64


In [6]:
#2. Check if a NumPy array has data type float64.
arr = np.array([1.5, 2.5, 3.5])

print(arr.dtype == np.float64)

True


In [7]:
#3. Create a NumPy array with complex128 data type.
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

print(arr)
print(arr.dtype)

[1.+2.j 3.+4.j 5.+6.j]
complex128


In [8]:
#4. Convert an integer array to float32.
arr = np.array([1, 2, 3, 4, 5])

arr = arr.astype(np.float32)

print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float32


In [9]:
#5. Convert float64 to float32.
arr = np.array([1.234567, 2.345678, 3.456789], dtype=np.float64)

arr = arr.astype(np.float32)

print(arr)
print(arr.dtype)

[1.234567 2.345678 3.456789]
float32


In [10]:
#6. Function to return shape, size, and data type.
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(array_attributes(arr))

((2, 3), 6, dtype('int64'))


In [11]:
#7. Function to return dimensionality.
def array_dimension(arr):
    return arr.ndim

arr = np.array([[1, 2], [3, 4]])

print(array_dimension(arr))

2


In [12]:
#8. Function to return item size and total size in bytes.
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

arr = np.array([1, 2, 3, 4])

print(item_size_info(arr))

(8, 32)


In [13]:
#9. Function to return array strides.
def array_strides(arr):
    return arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(array_strides(arr))

(24, 8)


In [14]:
#10. Function to return shape and strides.
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(shape_stride_relationship(arr))

((2, 3), (24, 8))


In [15]:
#11. Create an array of zeros with n elements.
def create_zeros_array(n):
    return np.zeros(n)

print(create_zeros_array(5))

[0. 0. 0. 0. 0.]


In [16]:
#12. Create a matrix of ones.
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

print(create_ones_matrix(3, 4))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
#13. Generate an array using start, stop and step.
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

print(generate_range_array(1, 10, 2))

[1 3 5 7 9]


In [18]:
#14. Generate equally spaced values.
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

print(generate_linear_space(0, 10, 5))

[ 0.   2.5  5.   7.5 10. ]


In [19]:
#15. Create an identity matrix using numpy.eye.
def create_identity_matrix(n):
    return np.eye(n)

print(create_identity_matrix(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
#16. Convert a Python list into a NumPy array.
def list_to_array(my_list):
    return np.array(my_list)

print(list_to_array([1, 2, 3, 4, 5]))

[1 2 3 4 5]


In [21]:
#17. Demonstrate numpy.view.
arr = np.array([1, 2, 3, 4, 5])

view_arr = arr.view()

view_arr[0] = 100

print("Original:", arr)
print("View:", view_arr)

Original: [100   2   3   4   5]
View: [100   2   3   4   5]


In [22]:
#18. Concatenate two arrays along a specified axis.
def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(concatenate_arrays(arr1, arr2, axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [23]:
#19. Concatenate two arrays horizontally.
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

result = np.concatenate((arr1, arr2), axis=1)

print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [24]:
#20. Vertically stack multiple arrays.
def vertical_stack(arrays):
    return np.vstack(arrays)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

print(vertical_stack([arr1, arr2, arr3]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
#21. Create integers within a specified range with a step.
def integer_range(start, stop, step):
    return np.arange(start, stop + 1, step)

print(integer_range(1, 10, 2))

[1 3 5 7 9]


In [26]:
#22. Generate 10 equally spaced values between 0 and 1.
arr = np.linspace(0, 1, 10)

print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [27]:
#23. Generate 5 logarithmically spaced values between 1 and 1000.
arr = np.logspace(0, 3, 5)

print(arr)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [2]:
#24. Create a Pandas DataFrame using a NumPy array.
arr = np.random.randint(1, 101, size=(5, 3))

df = pd.DataFrame(arr)

print(df)

    0   1   2
0  92  37  44
1  78  80  16
2  12  91  96
3  83  48  31
4  43  49  78


In [3]:
#25. Replace negative values in a DataFrame column with zero.
def replace_negative_values(df, column):
    df[column] = np.where(df[column] < 0, 0, df[column])
    return df

df = pd.DataFrame({
    "A": [10, -5, 20, -2, 15]
})

print(replace_negative_values(df, "A"))

    A
0  10
1   0
2  20
3   0
4  15


In [4]:
#26. Access the 3rd element.
arr = np.array([10, 20, 30, 40, 50])

print(arr[2])

30


In [5]:
#27. Retrieve the element at index (1, 2).
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr_2d[1, 2])

6


In [6]:
#28. Extract elements greater than 5.
arr = np.array([3, 8, 2, 10, 5, 7])

result = arr[arr > 5]

print(result)

[ 8 10  7]


In [7]:
#29. Slice elements from index 2 to 5 inclusive.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

result = arr[2:6]

print(result)

[3 4 5 6]


In [8]:
#30. Extract [[2, 3], [5, 6]].
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

result = arr_2d[0:2, 1:3]

print(result)

[[2 3]
 [5 6]]


In [9]:
#31. Extract elements in a specific order using indices.
def extract_elements(arr, rows, cols):
    return arr[rows, cols]

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

rows = np.array([0, 1, 2])
cols = np.array([2, 0, 1])

print(extract_elements(arr, rows, cols))

[3 4 8]


In [10]:
#32. Filter elements greater than a threshold.
def filter_greater_than(arr, threshold):
    return arr[arr > threshold]

arr = np.array([2, 5, 8, 10, 15])

print(filter_greater_than(arr, 7))

[ 8 10 15]


In [11]:
#33. Extract elements from a 3D array using three index arrays.
def extract_3d(arr, x, y, z):
    return arr[x, y, z]

arr = np.arange(27).reshape(3, 3, 3)

x = np.array([0, 1, 2])
y = np.array([1, 2, 0])
z = np.array([2, 0, 1])

print(extract_3d(arr, x, y, z))

[ 5 15 19]


In [12]:
#34. Extract elements satisfying two conditions.
def filter_two_conditions(arr):
    return arr[(arr > 5) & (arr < 15)]

arr = np.array([2, 6, 8, 12, 15, 20])

print(filter_two_conditions(arr))

[ 6  8 12]


In [13]:
#35. Extract elements using separate row and column indices.
def extract_by_indices(arr, rows, cols):
    return arr[rows, cols]

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

rows = np.array([0, 1, 2])
cols = np.array([1, 2, 0])

print(extract_by_indices(arr, rows, cols))

[2 6 7]


In [14]:
#36. Add 5 to every element using broadcasting.
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

result = arr + 5

print(result)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [15]:
#37. Multiply rows using broadcasting.
arr1 = np.array([1, 2, 3])
arr2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

result = arr2 * arr1.reshape(3, 1)

print(result)

[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


In [16]:
#38. Add an array to each row using broadcasting.
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [100, 110, 120]
])

result = arr2 + arr1.reshape(4, 1)

print(result)

[[ 11  21  31]
 [ 42  52  62]
 [ 73  83  93]
 [104 114 124]]


In [17]:
#39. Add arrays of shapes (3,1) and (1,3).
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[10, 20, 30]])

result = arr1 + arr2

print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [18]:
#40. Handle incompatible broadcasting shapes.
arr1 = np.ones((2, 3))
arr2 = np.ones((2, 2))

try:
    result = arr1 * arr2
    print(result)
except ValueError:
    print("The arrays have incompatible shapes for broadcasting.")

The arrays have incompatible shapes for broadcasting.


In [19]:
#41. Calculate column-wise mean.
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

column_mean = np.mean(arr, axis=0)

print(column_mean)

[4. 5. 6.]


In [20]:
#42. Find maximum value in each row.
arr = np.array([
    [1, 8, 3],
    [9, 2, 6],
    [4, 7, 5]
])

print(np.max(arr, axis=1))

[8 9 7]


In [21]:
#43. Find indices of maximum value in each column.
arr = np.array([
    [1, 8, 3],
    [9, 2, 6],
    [4, 7, 5]
])

print(np.argmax(arr, axis=0))

[1 0 1]


In [22]:
#44. Calculate moving sum along rows.
def moving_sum(arr, window):
    result = []

    for row in arr:
        row_result = np.convolve(row, np.ones(window, dtype=int), mode="valid")
        result.append(row_result)

    return np.array(result)

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print(moving_sum(arr, 2))

[[ 3  5  7]
 [11 13 15]]


In [23]:
#45. Check if all elements in each column are even.
arr = np.array([
    [2, 4, 6],
    [3, 5, 7]
])

result = np.all(arr % 2 == 0, axis=0)

print(result)

[False False False]


In [24]:
#46. Reshape an array into m rows and n columns.
def reshape_array(arr, m, n):
    return arr.reshape(m, n)

arr = np.arange(12)

print(reshape_array(arr, 3, 4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
#47. Flatten a matrix.
def flatten_array(matrix):
    return matrix.flatten()

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(flatten_array(matrix))

[1 2 3 4 5 6]


In [26]:
#48. Concatenate two arrays along a specified axis.
def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(concatenate_arrays(arr1, arr2, axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [27]:
#49. Split an array into multiple sub-arrays.
def split_array(arr, sections, axis=0):
    return np.array_split(arr, sections, axis=axis)

arr = np.arange(12)

print(split_array(arr, 3))

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]


In [28]:
#50. Insert and delete elements at specified indices.
def insert_delete_elements(arr, insert_indices, values, delete_indices):
    arr = np.insert(arr, insert_indices, values)
    arr = np.delete(arr, delete_indices)
    return arr

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result = insert_delete_elements(
    original_array,
    indices_to_insert,
    values_to_insert,
    indices_to_delete
)

print(result)

[ 1 10  4 11  5]


In [29]:
#51. Element-wise addition.
arr1 = np.random.randint(1, 11, 5)
arr2 = np.arange(1, 6)

result = arr1 + arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Addition:", result)

arr1: [10 10  2 10  5]
arr2: [1 2 3 4 5]
Addition: [11 12  5 14 10]


In [30]:
#52. Element-wise subtraction.
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)

result = arr1 - arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Subtraction:", result)

arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Subtraction: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [31]:
#53. Element-wise multiplication.
arr1 = np.random.randint(1, 11, 5)
arr2 = np.arange(1, 6)

result = arr1 * arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Multiplication:", result)

arr1: [ 6  3  8 10  4]
arr2: [1 2 3 4 5]
Multiplication: [ 6  6 24 40 20]


In [32]:
#54. Element-wise division.
arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)

result = arr1 / arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Division:", result)

arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
Division: [2. 2. 2. 2. 2.]


In [33]:
#55. Element-wise exponentiation.
arr1 = np.arange(1, 6)
arr2 = np.arange(5, 0, -1)

result = arr1 ** arr2

print(result)

[ 1 16 27 16  5]


In [34]:
#56. Count occurrences of a substring.
def count_substring(arr, substring):
    count = 0

    for item in arr:
        count += item.count(substring)

    return count

arr = np.array(["hello", "world", "hello", "numpy", "hello"])

print(count_substring(arr, "hello"))

3


In [35]:
#57. Extract uppercase characters from strings.
def extract_uppercase(arr):
    result = []

    for word in arr:
        uppercase = ''.join(char for char in word if char.isupper())
        result.append(uppercase)

    return np.array(result)

arr = np.array(["Hello", "World", "OpenAI", "GPT"])

print(extract_uppercase(arr))

['H' 'W' 'OAI' 'GPT']


In [36]:
#58. Replace occurrences of a substring.
def replace_substring(arr, old, new):
    return np.array([item.replace(old, new) for item in arr])

arr = np.array(["hello", "world", "hello", "numpy"])

print(replace_substring(arr, "hello", "hi"))

['hi' 'world' 'hi' 'numpy']


In [37]:
#59. Concatenate strings element-wise.
def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(["Hello", "Good"])
arr2 = np.array(["World", "Morning"])

print(concatenate_strings(arr1, arr2))

['HelloWorld' 'GoodMorning']


In [38]:
#60. Find the length of the longest string.
def longest_string_length(arr):
    return max(len(item) for item in arr)

arr = np.array(["apple", "banana", "grape", "pineapple"])

print(longest_string_length(arr))

9


In [39]:
#61. Mean, median, variance and standard deviation.
data = np.random.randint(1, 1001, 100)

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Variance:", np.var(data))
print("Standard Deviation:", np.std(data))

Mean: 473.32
Median: 450.5
Variance: 83624.25759999998
Standard Deviation: 289.17859118544715


In [40]:
#62. Find 25th and 75th percentiles.
data = np.random.uniform(1, 100, 50)

print("25th Percentile:", np.percentile(data, 25))
print("75th Percentile:", np.percentile(data, 75))

25th Percentile: 26.20512129110005
75th Percentile: 66.63481339661807


In [41]:
#63. Calculate correlation coefficient.
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 4, 6, 8, 10])

correlation = np.corrcoef(arr1, arr2)

print(correlation)

[[1. 1.]
 [1. 1.]]


In [42]:
#64. Matrix multiplication using dot.
matrix1 = np.array([
    [1, 2],
    [3, 4]
])

matrix2 = np.array([
    [5, 6],
    [7, 8]
])

result = np.dot(matrix1, matrix2)

print(result)

[[19 22]
 [43 50]]


In [43]:
#65. Calculate 10th, 50th, 90th percentiles and quartiles.
arr = np.random.randint(10, 1001, 50)

print("10th Percentile:", np.percentile(arr, 10))
print("50th Percentile:", np.percentile(arr, 50))
print("90th Percentile:", np.percentile(arr, 90))
print("First Quartile:", np.percentile(arr, 25))
print("Third Quartile:", np.percentile(arr, 75))

10th Percentile: 147.9
50th Percentile: 556.5
90th Percentile: 921.9
First Quartile: 299.25
Third Quartile: 765.75


In [44]:
#66. Find the index of a specific element.
arr = np.array([10, 20, 30, 40, 50])
element = 30

index = np.where(arr == element)[0]

print(index)

[2]


In [45]:
#67. Sort a random array in ascending order.
arr = np.random.randint(1, 101, 10)

print("Original:", arr)
print("Sorted:", np.sort(arr))

Original: [48 69 44 39  7 16 70 50 61 85]
Sorted: [ 7 16 39 44 48 50 61 69 70 85]


In [46]:
#68. Filter elements greater than 20.
arr = np.array([12, 25, 6, 42, 8, 30])

result = arr[arr > 20]

print(result)

[25 42 30]


In [47]:
#69. Filter elements divisible by 3.
arr = np.array([1, 5, 8, 12, 15])

result = arr[arr % 3 == 0]

print(result)

[12 15]


In [48]:
#70. Filter elements between 20 and 40 inclusive.
arr = np.array([10, 20, 30, 40, 50])

result = arr[(arr >= 20) & (arr <= 40)]

print(result)


[20 30 40]


In [49]:
#71. Check byte order using dtype.byteorder.
arr = np.array([1, 2, 3], dtype=np.int32)

print("Byte order:", arr.dtype.byteorder)

Byte order: =


In [50]:
#72. Perform byte swapping in place.
arr = np.array([1, 2, 3], dtype=np.int32)

arr.byteswap(inplace=True)

print(arr)

[16777216 33554432 50331648]


In [52]:
#73. Swap byte order without modifying the original array.

#For current NumPy versions, dtype.newbyteorder() can be used to construct the swapped dtype.

arr = np.array([1, 2, 3], dtype=np.int32)

swapped = arr.view(arr.dtype.newbyteorder())

print("Original:", arr)
print("Swapped:", swapped)

Original: [1 2 3]
Swapped: [16777216 33554432 50331648]


In [53]:
#74. Conditionally swap byte order based on system endianness.
arr = np.array([1, 2, 3], dtype=np.int32)

if arr.dtype.byteorder in ('=', '|'):
    print("Native byte order:", arr.dtype.byteorder)
else:
    arr = arr.view(arr.dtype.newbyteorder())

print(arr)

Native byte order: =
[1 2 3]


In [54]:
#75. Check whether byte swapping is necessary.
arr = np.array([1, 2, 3], dtype=np.int32)

if arr.dtype.byteorder == '=':
    print("No byte swapping is required.")
elif arr.dtype.byteorder == '|':
    print("Byte order is not applicable.")
else:
    print("Check system endianness before swapping.")

No byte swapping is required.


In [55]:
#76. Create a copy and modify it.
arr1 = np.arange(1, 11)

copy_arr = arr1.copy()

copy_arr[0] = 100

print("Original array:", arr1)
print("Copy:", copy_arr)

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Copy: [100   2   3   4   5   6   7   8   9  10]


In [56]:
#77. Create a slice and modify it.
matrix = np.random.randint(1, 20, (3, 3))

view_slice = matrix[:2, :2]

print("Original matrix:")
print(matrix)

view_slice[0, 0] = 999

print("Modified matrix:")
print(matrix)

Original matrix:
[[ 2 15  2]
 [11 10  3]
 [ 9 13  7]]
Modified matrix:
[[999  15   2]
 [ 11  10   3]
 [  9  13   7]]


In [57]:
#78. Broadcast addition to a slice.
array_a = np.arange(1, 13).reshape(4, 3)

view_b = array_a[1:3, :]

view_b += 5

print(array_a)

[[ 1  2  3]
 [ 9 10 11]
 [12 13 14]
 [10 11 12]]


In [58]:
#79. Reshaped view.
orig_array = np.arange(1, 9).reshape(2, 4)

reshaped_view = orig_array.reshape(4, 2)

reshaped_view[0, 0] = 100

print("Original array:")
print(orig_array)

print("Reshaped view:")
print(reshaped_view)

Original array:
[[100   2   3   4]
 [  5   6   7   8]]
Reshaped view:
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [59]:
#80. Create a copy using boolean indexing.
data = np.random.randint(1, 11, (3, 4))

data_copy = data[data > 5].copy()

if data_copy.size > 0:
    data_copy[0] = 999

print("Original data:")
print(data)

print("Copy:")
print(data_copy)

Original data:
[[ 9  1  3  1]
 [ 3  8  4  7]
 [10  4  1 10]]
Copy:
[999   8   7  10  10]


In [60]:
#81. Matrix addition and subtraction.
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Addition:")
print(A + B)

print("Subtraction:")
print(A - B)

Addition:
[[ 6  8]
 [10 12]]
Subtraction:
[[-4 -4]
 [-4 -4]]


In [61]:
#82. Matrix multiplication of C (3x2) and D (2x4).
C = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

D = np.array([
    [7, 8, 9, 10],
    [11, 12, 13, 14]
])

result = np.dot(C, D)

print(result)

[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [62]:
#83. Find the transpose of matrix E.
E = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(E.T)

[[1 4]
 [2 5]
 [3 6]]


In [63]:
#84. Calculate the determinant of square matrix F.
F = np.array([
    [1, 2],
    [3, 4]
])

determinant = np.linalg.det(F)

print("Determinant:", determinant)

Determinant: -2.0000000000000004


In [64]:
#85. Find the inverse of square matrix G.
G = np.array([
    [1, 2],
    [3, 4]
])

inverse = np.linalg.inv(G)

print("Inverse:")
print(inverse)

Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]
